version: 2.1
jobs: 
  image: "ubuntu-2004:202101-01"
  resource_class: xlarge
  sync_script: "bash ../../sync"
  build_script: "bash ../../build"
  upload_ccache_script: "bash ../../upload_ccache"

        
