version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01

      task:
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache
